export const internships = [
    {
        id: "1",
        title: "Webアプリ開発インターン",
        company: "テクノ株式会社",
        location: "名古屋市中区",
        workStyle: "ハイブリッド",
        period: "3ヶ月〜1年",
        workDays: "週3日〜",
        salary: "時給1,200円〜",
        description:
        "実際のプロジェクトに参加し、Webアプリケーション開発の実務経験を積むことができます。React、Next.jsなどのモダンな技術スタックを使用します。",
        tags: ["IT", "プログラミング", "名古屋"],
        graduationYears: ["27卒", "28卒"],
        logo: "/placeholder.svg?height=80&width=80",
        publishedAt: "2025/4/15",
        featured: true,
    },
    {
        id: "2",
        title: "マーケティングアシスタント",
        company: "三河デジタル",
        location: "豊橋市",
        workStyle: "リモート可",
        period: "6ヶ月〜",
        workDays: "週2日〜",
        salary: "時給1,100円〜",
        description:
        "デジタルマーケティングの実務を経験できるインターンシップです。SNS運用、コンテンツ制作、データ分析などを担当していただきます。",
        tags: ["マーケティング", "デジタル", "愛知"],
        graduationYears: ["27卒", "28卒", "29卒"],
        logo: "/placeholder.svg?height=80&width=80",
        publishedAt: "2025/4/14",
        featured: true,
    },
    {
        id: "3",
        title: "営業アシスタント",
        company: "東海商事",
        location: "静岡市葵区",
        workStyle: "オフィス",
        period: "3ヶ月〜",
        workDays: "週3日〜",
        salary: "時給1,000円〜",
        description:
        "法人営業のサポート業務を通じて、ビジネスの基礎を学べるインターンシップです。顧客対応や提案資料作成などを経験できます。",
        tags: ["営業", "法人営業", "静岡"],
        graduationYears: ["27卒"],
        logo: "/placeholder.svg?height=80&width=80",
        publishedAt: "2025/4/13",
        featured: false,
    },
    {
        id: "4",
        title: "UI/UXデザイナーアシスタント",
        company: "テクノ株式会社",
        location: "名古屋市中区",
        workStyle: "ハイブリッド",
        period: "6ヶ月〜",
        workDays: "週3日〜",
        salary: "時給1,300円〜",
        description:
        "Webサービスのデザイン業務を経験できるインターンシップです。実際のプロダクトのUI/UXデザインに携わることができます。",
        tags: ["デザイン", "UI/UX", "名古屋"],
        graduationYears: ["27卒", "28卒"],
        logo: "/placeholder.svg?height=80&width=80",
        publishedAt: "2025/4/12",
        featured: false,
    },
    {
        id: "5",
        title: "経営企画アシスタント",
        company: "中部産業",
        location: "岐阜市",
        workStyle: "オフィス",
        period: "6ヶ月〜1年",
        workDays: "週2日〜",
        salary: "時給1,100円〜",
        description:
        "経営企画部門でのインターンシップです。市場調査、データ分析、事業計画策定のサポートなどを担当していただきます。",
        tags: ["経営企画", "データ分析", "岐阜"],
        graduationYears: ["27卒"],
        logo: "/placeholder.svg?height=80&width=80",
        publishedAt: "2025/4/10",
        featured: false,
    },
    {
        id: "6",
        title: "研究開発アシスタント",
        company: "中部研究所",
        location: "浜松市中区",
        workStyle: "オフィス",
        period: "6ヶ月〜1年",
        workDays: "週3日〜",
        salary: "時給1,200円〜",
        description:
        "研究開発部門でのインターンシップです。新素材の研究開発プロジェクトに参加し、実験や分析業務を担当していただきます。",
        tags: ["研究", "開発", "静岡"],
        graduationYears: ["27卒", "28卒"],
        logo: "/placeholder.svg?height=80&width=80",
        publishedAt: "2025/4/8",
        featured: false,
    },
]