export const companies = [
    {
      id: "1",
      name: "テクノ株式会社",
      industry: "IT・通信",
      location: "名古屋市中区",
      description: "Webアプリケーション開発、システム開発、ITコンサルティング",
      employeeCount: "120名",
      logo: "/placeholder.svg?height=120&width=120",
      coverImage: "/placeholder.svg?height=200&width=400",
      jobCount: 3,
    },
    {
      id: "2",
      name: "東海商事",
      industry: "商社",
      location: "静岡市葵区",
      description: "自動車部品、電子部品の輸出入および販売",
      employeeCount: "250名",
      logo: "/placeholder.svg?height=120&width=120",
      coverImage: "/placeholder.svg?height=200&width=400",
      jobCount: 2,
    },
    {
      id: "3",
      name: "中部産業",
      industry: "製造業",
      location: "岐阜市",
      description: "自動車部品、精密機械部品の製造",
      employeeCount: "450名",
      logo: "/placeholder.svg?height=120&width=120",
      coverImage: "/placeholder.svg?height=200&width=400",
      jobCount: 4,
    },
    {
      id: "4",
      name: "三河デジタル",
      industry: "IT・通信",
      location: "豊橋市",
      description: "デジタルマーケティング、Webサイト制作",
      employeeCount: "80名",
      logo: "/placeholder.svg?height=120&width=120",
      coverImage: "/placeholder.svg?height=200&width=400",
      jobCount: 2,
    },
    {
      id: "5",
      name: "東海人材",
      industry: "人材サービス",
      location: "名古屋市中村区",
      description: "人材紹介、人材派遣、採用コンサルティング",
      employeeCount: "150名",
      logo: "/placeholder.svg?height=120&width=120",
      coverImage: "/placeholder.svg?height=200&width=400",
      jobCount: 1,
    },
    {
      id: "6",
      name: "中部研究所",
      industry: "研究・開発",
      location: "浜松市中区",
      description: "材料研究、製品開発、技術コンサルティング",
      employeeCount: "90名",
      logo: "/placeholder.svg?height=120&width=120",
      coverImage: "/placeholder.svg?height=200&width=400",
      jobCount: 2,
    },
  ]